language: node_js

before_install:
  - yes | gem update --system --force
  - gem install bundler

# TODO: consider extracting this to a bootstrap script
install:
  - rvm install $(cat .ruby-version)
  - bundle install
  - npm install
  # Don't think we need to manually do elm-package install, as tests are packaged by separate code.

script:
  - make elm-test
  - make cucumber
